#!/usr/bin/env bash

path_sep="/"

# Now we need to set the data path directories in guiconf.txt
default_data_path="$HOME"


inst_work=${1%$path_sep}
inst_data=${2%$path_sep}

echo "Work directory: $inst_work"
echo "Data directory: $inst_data"

# Substitute all the lines in dripconf.txt to match the current path
# installation
echo "Modifying CALDATA in dripconf.txt..."
perl -pi -e "s|.*caldata\s*=.*|CALDATA='$inst_data${path_sep}'|i" $inst_work${path_sep}dripconf.txt

# Substitute all the lines in guiconf.txt to match the current path
# installation
echo "Modifying AUTO_LISTFILE in guiconf.txt..."
perl -pi -e "s|.*auto_listfile\s*=.*|AUTO_LISTFILE='$inst_work${path_sep}autopipetest.log'|i" $inst_work${path_sep}guiconf.txt
echo "Modifying LOGFILE in guiconf.txt..."
perl -pi -e "s|.*logfile\s*=.*|LOGFILE = '$inst_work${path_sep}driplog.log'|i" $inst_work${path_sep}guiconf.txt


echo "Default paths are set to $default_data_path"

# Modify LOADDATAPATH in guiconf.txt
while :
do
  echo -n "Enter directory containing input data ($default_data_path): "
  read loaddatapath
  if [[ $loaddatapath == "" ]]; then
    loaddatapath=$default_data_path
  fi
  if [[ -d $loaddatapath ]]; then 
    if [[ -r $loaddatapath ]]; then
      break
    else 
      echo "You do not have reading permissions to this directory"
    fi
  else
    echo "This directory does not exist"
  fi
done
if [[ "${loaddatapath#${loaddatapath%?}}" != "${path_sep}" ]]; then 
  loaddatapath="$loaddatapath${path_sep}"
fi
echo "Modifying LOADDATAPATH in guiconf.txt..."
echo "        Input loaddatapath is $loaddatapath" 
perl -pi -e "s|.*loaddatapath\s*=.*|LOADDATAPATH='$loaddatapath'|i" $inst_work${path_sep}guiconf.txt
default_data_path=$loaddatapath

# Modify SAVEPATH in guiconf.txt
while :
do
  echo -n "Enter directory to save final products ($default_data_path): "
  read loaddatapath
  if [[ $loaddatapath == "" ]]; then
    loaddatapath=$default_data_path
  fi
  if [[ -d $loaddatapath ]]; then 
    if [[ -w $loaddatapath ]]; then
      break
    else 
      echo "You do not have writing permissions to this directory"
    fi
  else
    echo "This directory does not exist"
  fi
done
if [[ "${loaddatapath#${loaddatapath%?}}" != "${path_sep}" ]]; then 
  loaddatapath="$loaddatapath${path_sep}"
fi
echo "Modifying SAVEPATH in guiconf.txt..."
echo "        Input savepath is $loaddatapath" 
perl -pi -e "s|.*savepath\s*=.*|SAVEPATH='$loaddatapath'|i" $inst_work${path_sep}guiconf.txt
default_data_path=$loaddatapath

# Modify SAVECALPATH in guiconf.txt
while :
do
  echo -n "Enter directory to save calibration products ($default_data_path): "
  read loaddatapath
  if [[ $loaddatapath == "" ]]; then
    loaddatapath=$default_data_path
  fi
  if [[ -d $loaddatapath ]]; then 
    if [[ -w $loaddatapath ]]; then
      break
    else 
      echo "You do not have writing permissions to this directory"
    fi
  else
    echo "This directory does not exist"
  fi
done
if [[ "${loaddatapath#${loaddatapath%?}}" != "${path_sep}" ]]; then 
  loaddatapath="$loaddatapath${path_sep}"
fi
echo "Modifying SAVECALPATH in guiconf.txt..."
echo "        Input savecalpath is $loaddatapath" 
perl -pi -e "s|.*savecalpath\s*=.*|SAVECALPATH='$loaddatapath'|i" $inst_work${path_sep}guiconf.txt
default_data_path=$loaddatapath

exit 0
